[package]
name = "hbs-stack-overflow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
    sha3 = "0.10.1"
    num = "0.4.0"
    rand = "0.8.5"
    rand_chacha = "0.3.1"
    hbs-lms = "*"
